[build]
	publish = "_site"
	command = "npm run build"

[build.processing]
	skip_processing = false
[build.processing.css]
	bundle = true
	minify = true
[build.processing.js]
	bundle = true
	minify = true
[build.processing.images]
	compress = true

[context.branch-deploy.environment]
	NODE_VERSION = "16.0.0"

[[plugins]]
	package = "netlify-plugin-cache"

	[plugins.inputs]
	paths = [
		"_site/static/images/art/built/",
		"_site/static/images/avatars/built/",
		"_site/static/images/graphic/built/",
		"_site/static/images/photography/built/",
		"_site/static/images/writing/built/"
	]

[[redirects]]
	from = "http://gabriellewee.netlify.app/*"
	to = "http://gabriellew.ee/:splat"
	status = 301
	force = true

[[redirects]]
	from = "https://gabriellewee.netlify.app/*"
	to = "https://gabriellew.ee/:splat"
	status = 301
	force = true

[[redirects]]
	from = "/v1/*"
	to = "https://archive.gabriellew.ee/v1/:splat"
	status = 200
	force = true

[[redirects]]
	from = "/v2/*"
	to = "https://archive.gabriellew.ee/v2/:splat"
	status = 200
	force = true

[[redirects]]
	from = "/v3/*"
	to = "https://archive.gabriellew.ee/v3/:splat"
	status = 200
	force = true

[[redirects]]
	from = "/v4/*"
	to = "https://archive.gabriellew.ee/v4/:splat"
	status = 200
	force = true

[[redirects]]
	from = "/nameplate/v1/*"
	to = "https://archive.gabriellew.ee/nameplate/v1/:splat"
	status = 200
	force = true

[[redirects]]
	from = "/nameplate/v2/*"
	to = "https://archive.gabriellew.ee/nameplate/v2/:splat"
	status = 200
	force = true