[build]
	publish = "_site"
	command = "npm run build"

[build.processing]
	skip_processing = false
[build.processing.css]
	bundle = true
	minify = true
[build.processing.js]
	bundle = false
	minify = true
[build.processing.images]
	compress = true